#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Installing display listener...\n"
sudo cp listen-display.py /usr/local/bin/
sudo chmod +x /usr/local/bin/listen-display.py

echo "=> Starting display listener...\n"
sudo cp listen-display.sh /etc/init.d/
sudo chmod +x /etc/init.d/listen-display.sh

sudo update-rc.d listen-display.sh defaults
sudo /etc/init.d/listen-display.sh start

echo "Display listener installed."
